import type { Metadata } from 'next';
import { BookOpen, Database, Droplet, ShieldCheck, Users } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { themeRecords } from '@/lib/theme-data';

export const metadata: Metadata = { title: '關於展覽與資料來源｜水水客庄', description: '了解水水客庄的策展目的、雙層架構、資料責任與素材來源。' };

export default function AboutPage() {
  const principles = [{ icon: Droplet, title: '從水理解客庄', text: '以辨水、造水、分水、守水與共水，理解聚落如何形成。' }, { icon: Users, title: '服務不同觀眾', text: '故事、互動與研究三種深度，不以身分或註冊作為進入門檻。' }, { icon: Database, title: '資料可追溯', text: '保留典藏來源，清楚區分史料、口述、傳說與策展詮釋。' }, { icon: ShieldCheck, title: '尊重地方與個資', text: 'O2O 原型不使用定位、鏡頭或個資；正式合作須由地方與機關核定。' }];
  return <main className="min-h-screen bg-background pb-20 text-foreground md:pb-0"><SiteHeader /><section className="border-b-[3px] border-[#143f4f] bg-[#143f4f] px-5 py-20 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-black tracking-[.2em] text-[#75d4ed]">ABOUT THE EXHIBITION · 關於展覽</p><h1 className="mt-5 text-6xl font-black leading-[.95] tracking-[-.05em] sm:text-8xl">客庄如何<br /><span className="text-[#ffcb47]">被水塑造？</span></h1><p className="mt-7 max-w-3xl text-lg font-medium leading-9 text-white/70">「水水客庄」從物質水利與精神守護兩條路徑，帶觀眾走進六個獨立展區，再於水水書房匯集研究與地方知識。</p></div></section><section className="soft-grid px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1180px]"><h2 className="text-4xl font-black sm:text-6xl">雙層策展架構</h2><div className="mt-8 grid gap-6 md:grid-cols-2">{themeRecords.map((theme) => <a key={theme.slug} href={`/themes/${theme.slug}`} className="rounded-[30px] border-[3px] border-[#143f4f] bg-white p-7 shadow-[0_6px_0_#143f4f]"><span style={{ backgroundColor: theme.color }} className="inline-flex rounded-full border-2 border-[#143f4f] px-3 py-1 text-xs font-black">{theme.index}</span><h3 className="mt-4 text-4xl font-black">{theme.title}</h3><p className="mt-4 font-medium leading-8 text-[#5c747d]">{theme.description}</p><p className="mt-5 font-black text-[#148781]">包含三個獨立展區 →</p></a>)}</div><div className="mt-12 grid gap-5 sm:grid-cols-2">{principles.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-[26px] border-2 border-[#143f4f] bg-white p-6"><Icon className="size-8 text-[#148781]" /><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-2 text-sm font-medium leading-7 text-[#617880]">{text}</p></article>)}</div><div className="mt-12 rounded-[30px] border-[3px] border-[#143f4f] bg-[#ffcb47] p-7 shadow-[0_6px_0_#143f4f]"><BookOpen className="size-8" /><h2 className="mt-4 text-3xl font-black">資料與素材說明</h2><p className="mt-4 font-medium leading-8 text-[#506872]">策展原型依《水水客庄線上展示計畫服務建議書修訂版 v0.6》及後續架構調整製作。展示影像主要引用客家文化發展中心客家文化資產數位網；影音目前為委託人指定的功能示範。正式典藏編號、授權、策展團隊名單與合作場域，須於核定後補齊。</p><a href="/library" className="mt-6 inline-flex rounded-full border-2 border-[#143f4f] bg-white px-5 py-3 text-sm font-black">查看水水書房來源 →</a></div></div></section></main>;
}
